apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchplane.fullname" . }}-gateway
  labels:
    {{- include "matchplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "matchplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchplane.fullname" . }}-payment-service
  labels:
    {{- include "matchplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.paymentService.service.type }}
  selector:
    {{- include "matchplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: payment-service
  ports:
    - name: http
      port: {{ .Values.paymentService.service.port }}
      targetPort: http
{{- if .Values.conversionProjector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchplane.fullname" . }}-conversion-projector
  labels:
    {{- include "matchplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.conversionProjector.service.type }}
  selector:
    {{- include "matchplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: conversion-projector
  ports:
    - name: http
      port: {{ .Values.conversionProjector.service.port }}
      targetPort: http
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchplane.fullname" . }}-federation-hub
  labels:
    {{- include "matchplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.federationHub.service.type }}
  selector:
    {{- include "matchplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: federation-hub
  ports:
    - name: grpc
      port: {{ .Values.federationHub.service.port }}
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchplane.fullname" . }}-web
  labels:
    {{- include "matchplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "matchplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matchplane.fullname" . }}-matcher
  labels:
    {{- include "matchplane.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "matchplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: matcher
